
= High Error Drug (HED) Workflow

== Data locations

PFS is the shared, persistent, parallel file system.

`DATA_SOURCE`::
Original data in PFS.

`TMP-ORIGINAL`::
`/tmp/$USER/original`: location that data is loaded into from `DATA_SOURCE` by `hook-leader.tcl` .
Specified by hyperparameter `input_dir` .
Hard-coded in `hook-leader.tcl` and `dflts-*.json` .

`TMP-INSTANCE`::
`/tmp/$USER/index-00N`: location for partitioned data from `partition_uno_pq`.
`hed_setup` changes `input_dir` to this directory.
This is also the hyperparameter `instance_directory` and `output_dir` for the model run.
Set by `hed_setup`.  

== Components and controls

`upf-uno-heds.sh`::
The main user interface script.  Controls:
+
. `DATA_SOURCE`
. Software locations for IMPROVE and Uno

`cfg-sys-1.sh`::
System settings.  Controls:
+
. `PROCS`: The process count (number of ranks, including 1 server)
. `PPN`: The processes-per-node number
. `QUEUE`: The queue to use
+
All of these may be set in the user environment as well, which takes precedence.

`UPF`::
(Unrolled Parameter File: A hard-coded list of hyperparameters to run.)  The list of JSON hyperparameter sets to run.  Generated by `gen-jsons.py`

`DFLTS`::
The JSON hyperparameters to run for every instance.  Each instance combines this set with a set from the UPF.  Settings include `epochs`, `input_dir`==`TMP-ORIGINAL`.  Could be extended with other model hyperparameters, which will override Uno's `uno_default_model.txt`.

`hed_setup`::
Sets up and tears down the training run.  Called by Supervisor's `model_runner.py`.  No user controls.
+
. Before the run:
.. Calls `partition_uno_pq.py` to partition `rsp_merged.parquet` into `rsp_{train,val,test}_data.parquet` using the `index`.
. Sets up all training data in the `TMP-INSTANCE` location.
.. Sets up the XPU for Aurora
. After the run:
.. Touches the marker file for this `index` to prevent restart
.. Unlinks the `TMP-INSTANCE` files to save space.


== Aurora
